[package]
name = "nc-sim"
version = "0.1.0"
authors = ["Alissa Rao <lymia@lymiahugs.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
bitstream-io = "1.0.0"
byteorder = "1.4.3"
cesu8 = "1.1.0"
num_enum = "0.5.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
